# Yr widget
# URL to Yr XML data
yr:
  enabled: true
  url: http://www.yr.no/sted/Norge/S%C3%B8r-Tr%C3%B8ndelag/Trondheim/Trondheim/varsel.xml


# Uptime widget
# Label is the label displayed in the widget. Host can be a hostname or an IP
# address. The uptime job will send 1 ICMP packet to the given host, with a 1
# second timeout
uptime:
  devices:
    - label: Router
      host: 10.0.0.1
    - label: Computer A
      host: 10.0.0.10
    - label: Computer B
      host: 10.0.0.20


# Atb widget
# Replace yourLocationId with your closest locationId and yourApiKey with your
# issued API key.
# See http://wiki.busbuddy.no/doku.php for API docs
atb:
  url: http://api.busbuddy.no/api/1.4.4/departures/yourLocationId?apiKey=yourApiKey


# Plex widget
# Replace ip:port with the IP and port (default is 32400) of your Plex Media
# Server. The section number identifies the appropriate section.
plex:
  shows: http://ip:port/library/sections/1/recentlyAdded/
  movies: http://ip:port/library/sections/2/recentlyAdded/


# Calendar widget
# This widget requires read only access to your Google Calendar. To configure
# access please see:
# https://developers.google.com/google-apps/calendar/instantiate
calendar:
  mechanism: oauth_2
  scope: https://www.googleapis.com/auth/calendar.readonly
  client_id: client_id
  client_secret: client_secret
  access_token: access_token
  refresh_token: refresh_token
